### ISSUE TITLE
Need help with the layouting

### ISSUE THREAD

**Issue by tibudiyanto** [tibudiyanto/jakarta-vax-availability#1]
At the moment, it is not responsive enough on mobile device. 

Help is very appreciated!

**Comment by juaan** [comment]
I'd like to help mas, I tried to do a grouping location as well
<img width="1720" alt="Screen Shot 2021-07-05 at 11 02 42" src="https://user-images.githubusercontent.com/20969634/124416406-21a65280-dd81-11eb-8c7a-f5993721ebc6.png">

<img width="1720" alt="Screen Shot 2021-07-05 at 11 02 53" src="https://user-images.githubusercontent.com/20969634/124416394-1a7f4480-dd81-11eb-96aa-d28849c993c6.png">

**Comment by tibudiyanto** [comment]
Thank you @pveyes
