### ISSUE TITLE
Sort by location

### ISSUE THREAD

**Issue by tibudiyanto** [tibudiyanto/jakarta-vax-availability#2]
Under detail_lokasi there is a lat lon. Would be nice if we can ~~sort by lat lon~~ sort by current location to the vax location

**Comment by pveyes** [comment]
do you mean sort by distance from current location? just clarifying question for other people who might want to contribute :p

**Comment by tibudiyanto** [comment]
@pveyes Lol yea. Sort by distance of current location to the vax location

**Comment by agallio** [comment]
Added get current location function with a button. Still investigating on how to get the nearest vax location. [PR](https://github.com/tibudiyanto/jakarta-vax-availability/pull/6)

**Comment by tibudiyanto** [comment]
Added a comment on the PR!
