### ISSUE TITLE
Redesign - `VaxLocation` card

### ISSUE THREAD

**Issue by resir014** [tibudiyanto/jakarta-vax-availability#25]
## Tasks

- [x] #2 
- [x] #36
- [x] #38
- [x] #10 
- [x] #66
- [x] Apply redesigned VaxLocation card

**Comment by pveyes** [comment]
Can we add an indicator for location with 0 slots? I personally think it's useless to display the location, but maybe just a red border or something around the schedule button is fine

![image](https://user-images.githubusercontent.com/1614415/124465115-386b9a00-ddbf-11eb-8e11-4a8ffd238e88.png)

**Comment by resir014** [comment]
@pveyes This will need a rework on how we display each facilities' information in the VaxLocation card. We have a good start in #36, though.

**Comment by pveyes** [comment]
Agree, 36 is good enough for now

**Comment by resir014** [comment]
I quickly mocked together (in Tailwind CSS, lol) a possible redesign of the cards, right here:

![image](https://user-images.githubusercontent.com/5663877/124483110-2c3e0780-ddd4-11eb-94a5-9fbf06b2216f.png)

https://play.tailwindcss.com/qVoFc70Nmq

"Lihat Jadwal" will open up a modal showing the details + address, as well as the schedule.

![image](https://user-images.githubusercontent.com/5663877/124483178-3bbd5080-ddd4-11eb-91bf-f177a44314eb.png)

https://play.tailwindcss.com/mEWZ566LjS

Let me know if you have any comments, @pveyes.

**Comment by resir014** [comment]
Also @sonnylazuardi need to let me know if the above designs can be easily implemented on the map.

**Comment by sonnylazuardi** [comment]
i think it's possible to put it on map popover

**Comment by pveyes** [comment]
nice ❤️  it

**Comment by pveyes** [comment]
what if we move the empty slot label above distance so it doesn't take too much horizontal space like this

![image](https://user-images.githubusercontent.com/1614415/124487350-ca33d100-ddd8-11eb-9396-ffd1aba38ab0.png)

**Comment by resir014** [comment]
@pveyes yep, that could work!

**Comment by resir014** [comment]
All the subtasks are done, I should be able to spend a night tomorrow implementing this redesign!

**Comment by sonnylazuardi** [comment]
looking really good ✨ 

any chance we add tailwind to this repo? or chakra is enough?

**Comment by mazipan** [comment]
All the data is on uppercase character right now, it cause loss of focus.

I think we didn't need to show all the data in uppercase.
I mean, maybe we need to transform the data manually on the client, or it can be done on the API level (ideally it should be fix on the API)

The "faskes" name is okay to use an uppercase, but the rest are not ideal using uppercase.

**Comment by sonnylazuardi** [comment]
> All the data is on uppercase character right now, it cause loss of focus.
> 
> I think we didn't need to show all the data in uppercase.
> I mean, maybe we need to transform the data manually on the client, or it can be done on the API level (ideally it should be fix on the API)
> 
> The "faskes" name is okay to use an uppercase, but the rest are not ideal using uppercase.

It's already fixed here https://github.com/tibudiyanto/jakarta-vax-availability/pull/48

**Comment by resir014** [comment]
> any chance we add tailwind to this repo? or chakra is enough?

@sonnylazuardi We can try to re-implement these in Chakra UI, I don't mind, lol.

**Comment by broerjuang** [comment]
> I quickly mocked together (in Tailwind CSS, lol) a possible redesign of the cards, right here:
> 
> ![image](https://user-images.githubusercontent.com/5663877/124483110-2c3e0780-ddd4-11eb-94a5-9fbf06b2216f.png)
> 
> https://play.tailwindcss.com/qVoFc70Nmq
> 
> "Lihat Jadwal" will open up a modal showing the details + address, as well as the schedule.
> 
> ![image](https://user-images.githubusercontent.com/5663877/124483178-3bbd5080-ddd4-11eb-91bf-f177a44314eb.png)
> 
> https://play.tailwindcss.com/mEWZ566LjS
> 
> Let me know if you have any comments, @pveyes.

this looks great!

**Comment by resir014** [comment]
Decided to incrementally redesign this, instead of doing the whole thing as a "big bang" change. Current progress:

![image](https://user-images.githubusercontent.com/5663877/124752531-2b32e480-df52-11eb-9701-57c42897f176.png)

**Comment by resir014** [comment]
First phase of the redesign has a bug where it doesn't properly truncate. Tracking this in #66.

**Comment by pveyes** [comment]
I also notice that some location title is still uppercase 
![image](https://user-images.githubusercontent.com/1614415/124907034-e8384600-e011-11eb-9ea7-a87a196afe72.png)

**Comment by resir014** [comment]
@pveyes Yeah, I reverted the facility name to use the names as-is from the API. The remaining data (kec/kel, and kota administrasi) is still properly capitalised.

**Comment by pveyes** [comment]
I'm currently working on overflow fix, should I normalize it to capital or let it be uppercase?

**Comment by arieare** [comment]
IMO. Capital is better for readability, but we can't always know if a name contains an acronym.

**Comment by resir014** [comment]
@arieare Yes, capitals are good for title, but when the entire card is all caps (like the raw value that we get it from the API), it can lead to disorientation.

We had to do string manipulation because the name + kec/kel + kota adm. values we get are all caps, since as I said above, having the entire card in all caps is also not a good idea.

**Comment by syauqy** [comment]
![vax location card](https://media.giphy.com/media/RZkLRWoPtkvVKU3w5p/giphy.gif)
Hi All, I did some adjustments to the vax location card based on some references here. Put the location details, vax quota and schedules inside the drawer. 

Let me know what do you guys think. If it's okay, I'll make a new PR.
The drawer PR is #79

**Comment by resir014** [comment]
This issue is now finished! 🎉 

![image](https://user-images.githubusercontent.com/5663877/125930446-79ac65fc-859f-4529-ac73-4fa3688e384e.png)

Any further improvements to the card's design can be made as another issue/PR separate to this.

Thanks for the help <3
