### ISSUE TITLE
Add GitHub Actions CI for linting + type checking

### ISSUE THREAD

**Issue by resir014** [tibudiyanto/jakarta-vax-availability#28]

**Comment by pveyes** [comment]
cmiiw but doesn't next.js already do build-time type validation?

idk about lint, but given they recently launched eslint integration, we could probably just rely on vercel build

**Comment by resir014** [comment]
@pveyes Unfortunately the Vercel build logs atm are invisible to everyone outside of @tibudiyanto. This gives a nicer overview of lint results + type checks without having to go to Theo's Vercel dashboard, and also helps for in case we need to add unit tests later.

**Comment by pveyes** [comment]
ah yeah, good point, forgot about logs

**Comment by pveyes** [comment]
btw should we disable (ignore) lint & typecheck in next build after #52 lands?

**Comment by resir014** [comment]
@pveyes Yes, we should.
