### ISSUE TITLE
Map marker overlap with pop over

### ISSUE THREAD

**Issue by drgx** [tibudiyanto/jakarta-vax-availability#37]
![image](https://user-images.githubusercontent.com/5230095/124480344-5b06ae80-ddd1-11eb-8c39-c9845ab45aea.png)

**Comment by pveyes** [comment]
should be fixed in #30

**Comment by sonnylazuardi** [comment]
Fixed in https://github.com/tibudiyanto/jakarta-vax-availability/pull/56 🎉
