### ISSUE TITLE
UI overflow in the header card

### ISSUE THREAD

**Issue by resir014** [tibudiyanto/jakarta-vax-availability#66]
## Description

The `VaxLocation` card's header is currently overflowing and pushing the distance and quota badge out of view.

![image](https://user-images.githubusercontent.com/5663877/124906457-47498b00-e011-11eb-9e29-8732b631c976.png)

## Expected Behaviour

The `VaxLocation` card's header should properly truncate.

## Additional Information

Let's go back to the [Tailwind Play URL](https://play.tailwindcss.com/qVoFc70Nmq) from the mockup and take a look at which styles we're missing.

**Comment by utopictown** [comment]
will adding overflow: auto suffice?

![image](https://user-images.githubusercontent.com/42117448/124908083-1e29fa00-e013-11eb-9b8a-62149c259c04.png)

**Comment by pveyes** [comment]
@utopictown, no because the right side is also used display distance. I'm currently working on a fix
