### ISSUE TITLE
Missing "waktu" on "jadwal"

### ISSUE THREAD

**Issue by resir014** [tibudiyanto/jakarta-vax-availability#69]
## Description

With the recent changes to the API, it seems that the "waktu" property on "jadwal" has gone missing, therefore the time is missing from each schedule.

![image](https://user-images.githubusercontent.com/5663877/124908206-44e83080-e013-11eb-899a-de9751538d84.png)

## Expected Behaviour

The time should display properly on the schedule.

## Additional Information

It looks like the API schema has changed:

![image](https://user-images.githubusercontent.com/5663877/124908532-a01a2300-e013-11eb-8980-b26a66cc8c4e.png)

**Comment by mathdroid** [comment]
nice
